version: "3"
services:
    frontend:
        build: ./frontend
        container_name: front-bexs
        environment:
          - ENV=develop
          - SAMPLE_VAR_FOR_DEVELOPERS=example
        ports :
          - "8000:8000"            
        # volumes:
        #     - /this/app/dont/need/persistence
    backend:
        build: ./backend
        container_name: back-bexs
        environment:
          - ENV=develop
          - SAMPLE_VAR_FOR_DEVELOPERS=example
        ports :
          - "8080:8080"
        links:
          - frontend
        # volumes:
        #     - /this/app/also/dont/need/persistence